# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
# Comment the next line if you're not using Swift and don't want to use dynamic frameworks

target 'DYTV' do

  use_frameworks!

  # Pods for DYTV

  target 'DYTVTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DYTVUITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'Alamofire', '~> 4.0.1'
pod 'Kingfisher', '~> 3.1.4'
end
